### PR TITLE
Support Pipeline on Jenkinsfile Again

### PR DESCRIPTION
**Pull request by caryyu**
Support Pipeline on Jenkinsfile Again

### CODE REVIEW

**Comment by oleg-nenashev** [comment]
IIUC the plugin has no active maintainer

**Comment by caryyu** [comment]
@oleg-nenashev  this PR has been committed so long, no one takes an action.

**Comment by oleg-nenashev** [comment]
Well, I would ping @cchabanois at least.
Maybe he just missed the notification

**Comment by igreenfield** [comment]
@cchabanois  What is the status of that? this PR is needed!!!!

**Comment by BogdanLivadariu** [comment]
@igreenfield , @oleg-nenashev  , @caryyu 
consider raising a PR in which you request write access to this repository
https://github.com/jenkins-infra/repository-permissions-updater

**Comment by caryyu** [comment]
Hi everyone, Since it's been a long time for me not doing this relevant job, I'm gonna close this PR because I don't think I've got plenty of time to keep tracking and studying this loop here.

**Pull request closed without merging**
